# Generated by Django 5.1.7 on 2025-03-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#6200ee', help_text='Main color for buttons and highlights (hex code)', max_length=20, verbose_name='Primary Color')),
                ('primary_variant_color', models.CharField(default='#3700b3', help_text='Darker variant of primary color (hex code)', max_length=20, verbose_name='Primary Variant Color')),
                ('secondary_color', models.CharField(default='#03dac6', help_text='Accent color for secondary elements (hex code)', max_length=20, verbose_name='Secondary Color')),
                ('secondary_variant_color', models.CharField(default='#018786', help_text='Darker variant of secondary color (hex code)', max_length=20, verbose_name='Secondary Variant Color')),
                ('background_color', models.CharField(default='#ffffff', help_text='Main background color (hex code)', max_length=20, verbose_name='Background Color')),
                ('surface_color', models.CharField(default='#ffffff', help_text='Surface elements color (hex code)', max_length=20, verbose_name='Surface Color')),
                ('error_color', models.CharField(default='#b00020', help_text='Color for error states (hex code)', max_length=20, verbose_name='Error Color')),
                ('on_primary_color', models.CharField(default='#ffffff', help_text='Text color on primary background (hex code)', max_length=20, verbose_name='On Primary Color')),
                ('on_secondary_color', models.CharField(default='#000000', help_text='Text color on secondary background (hex code)', max_length=20, verbose_name='On Secondary Color')),
                ('on_background_color', models.CharField(default='#000000', help_text='Text color on main background (hex code)', max_length=20, verbose_name='On Background Color')),
                ('on_surface_color', models.CharField(default='#000000', help_text='Text color on surface elements (hex code)', max_length=20, verbose_name='On Surface Color')),
                ('on_error_color', models.CharField(default='#ffffff', help_text='Text color on error elements (hex code)', max_length=20, verbose_name='On Error Color')),
                ('font_family', models.CharField(default='Vazirmatn, sans-serif', help_text='Main font family for the website', max_length=100, verbose_name='Font Family')),
                ('heading_font_family', models.CharField(blank=True, help_text='Font family for headings (leave blank to use main font)', max_length=100, verbose_name='Heading Font Family')),
                ('border_radius', models.CharField(default='8px', help_text='Border radius for elements (e.g., 8px)', max_length=20, verbose_name='Border Radius')),
                ('hero_background_image', models.ImageField(blank=True, help_text='Background image for the hero section', null=True, upload_to='template/', verbose_name='Hero Background Image')),
                ('hero_overlay_opacity', models.DecimalField(decimal_places=2, default=0.5, help_text='Opacity for the dark overlay on hero image (0-1)', max_digits=3, verbose_name='Hero Overlay Opacity')),
                ('custom_css', models.TextField(blank=True, help_text='Additional custom CSS for the website', verbose_name='Custom CSS')),
                ('footer_background_color', models.CharField(default='#212529', help_text='Background color for the footer (hex code)', max_length=20, verbose_name='Footer Background Color')),
                ('footer_text_color', models.CharField(default='#ffffff', help_text='Text color for the footer (hex code)', max_length=20, verbose_name='Footer Text Color')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Template Settings',
                'verbose_name_plural': 'Template Settings',
            },
        ),
    ]
